if has("langmap")
    set langmap=dgDG
    set langmap+=ekEK
    set langmap+=feFE
    set langmap+=gtGT
    set langmap+=ilIL
    set langmap+=jyJY
    set langmap+=knKN
    set langmap+=luLU
    set langmap+=njNJ
    set langmap+=o\\;O:
    set langmap+=prPR
    set langmap+=rsRS
    set langmap+=sdSD
    set langmap+=tfTF
    set langmap+=uiUI
    set langmap+=yoYO
    set langmap+=\\;p:P
endif
